[package]
name = "block-explorer-backend"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
resolver = "2"
publish = false

[dependencies]
anyhow = "1"
axum = { version = "0.6" }
clap = { version = "4", features = ["derive", "env"] }
hex = "0.4"
indoc = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sov-celestia-adapter = { path = "../../adapters/celestia", features = ["native"], version = "0.2" }
sov-db = { path = "../../full-node/db/sov-db", version = "0.2" }
sov-modules-stf-template = { path = "../../module-system/sov-modules-stf-template", version = "0.2" }
sov-rollup-interface = { path = "../../rollup-interface", version = "0.2" }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls", "json"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
axum-test = "12"
block-explorer-backend = { path = "." }
demo-stf = { path = "../../examples/demo-stf" }
sov-risc0-adapter = { path = "../../adapters/risc0" }
sov-demo-rollup = { path = "../../examples/demo-rollup" }
sov-modules-api = { path = "../../module-system/sov-modules-api" }
sov-stf-runner = { path = "../../full-node/sov-stf-runner" }
sov-rng-da-service = { path = "../rng-da-service" }
tempfile = "3"
