[package]
name = "sov-fork-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
sov-state = { path = "../sov-state", version = "0.2", features = ["native"] }
sov-rollup-interface = { path = "../../rollup-interface", version = "0.2" }
sov-db = { path = "../../full-node/db/sov-db", version = "0.2" }
jmt = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
sov-rollup-interface = { path = "../../rollup-interface", features = ["mocks"] }